### ISSUE TITLE
[Task] SR 및 Wiki 보완

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#1]
### ISSUE
- Group: `SR`
- Type: `feature`
- Detail: 전체적인 SR 및 Wiki 보완

### TODO
 1. [x] Project Requirement 수정 및 구체화
 2. [x] Home, Readme 업데이트 
 3. [x] DB schema 작성

### Estimated time
 `1h`
