### ISSUE TITLE
[Task] 랜딩페이지- 스크롤 애니메이션 포함 애니메이션 효과들(텍스트, 원형 줌) 

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#12]
### ISSUE
- Group: client
- Type: feature
- Detail: 랜딩페이지- 스크롤 애니메이션 포함 애니메이션 효과들(텍스트, 원형 줌) 

### TODO
 1. [x] 첫번째 섹션 - 텍스트,검색바 애니메이션
 2. [x] 가운데 섹션 - 스크롤 애니메이션 - 텍스트, 특정 위치에서 이미지 줌
 3. [x] 하단 섹션 - 텍스트,검색바 애니메이션 

### Estimated time
`3h`
