### ISSUE TITLE
[Task] 검색 페이지 - 검색한 결과 렌더링 시 애니메이션

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#27]
### ISSUE
- Group: client
- Type: feature
- Detail: 검색 페이지 - 검색한 결과들 렌더링 시 원형으로 공중에 떠다니는 듯한 애니메이션

### TODO
 1. [x] useRef 이용 dom 접근
 2. [x] gsap 이용 타임라인 설정 후 애니메이션 효과 줄 엘리먼트들 연결
 3. [x] 원형들 애니메이션 거리, 시간 간격 자연스럽게 설정할 함수 작성

### Estimated time
 `3h`
