### ISSUE TITLE
[Task] 랜딩 페이지 기본 세팅 및 header, footer

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#5]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 랜딩 페이지 기본 세팅 및 header

### TODO
 1. [x] particle.js 로 배경 세팅
 2. [x] header - 로고, 메뉴 
 3. [x] header - 라이크/다크 모드 토글 css

### Estimated time
`3h`
