### ISSUE TITLE
[Task] 리덕스 세팅

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#52]
### ISSUE
- Group: client
- Type: feature
- Detail: 리덕스 세팅 후 검색 시 action 연동

### TODO
 1. [x] package.json에 리덕스 세팅
 2. [x] action, store, reducer 폴더 및 파일 생성 후 작성
 3. [x] 검색 기능에 연동 후 확인

### Estimated time

`2h`
