### ISSUE TITLE
[Task] 로그인, 회원가입 페이지 css 및 서버 통신 ( 클라이언트 )

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#61]
### ISSUE
- Group: client
- Type: feature
- Detail: 클라이언트 - 로그인, 회원가입 페이지 css 및 서버 통신

### TODO
 1. [x] 로그인 페이지 css
 2. [x] 회원가입 페이지 css
 3. [x] 로그인, 회원가입 이메일, 비밀번호 유효성 검사
 4. [x] 요청 로직 구현 후 응답 확인

### Estimated time
 `3h`
