### ISSUE TITLE
[Task] 로그인 시 헤더 css, 드랍박스 

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#63]
### ISSUE
- Group: client
- Type: feature
- Detail: 유저 로그인 시 헤더에 유저 프로필 이미지 렌더링, 유저 페이지 드랍박스

### TODO
 1. [x] 로그인 시 헤더에 원형 css로 유저 프로필 사진 렌더링
 2. [x] 네비게이션 용 유저 페이지 드랍박스
 3. [x] 각 페이지 서브 라우팅 및 링크

### Estimated time
 `3h`
