### ISSUE TITLE
[Task] 로그아웃, 회원 탈퇴  구현 

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#64]
### ISSUE
- Group: client
- Type: feature
- Detail: 로그아웃, 회원 탈퇴 구현 

### TODO
 1. [x] 로그아웃 요청 후 처리
 2. [x] 회원 탈퇴 요청 로직
 3. [x] 회원 탈퇴 요청 후 알림 모달

### Estimated time
 `2h`
