### ISSUE TITLE
[Task] 꿈 그림 페이지 - 그림 post (서버)

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#75]
### ISSUE
- Group: server
- Type:  feature
- Detail: 꿈 그림 페이지 - 그림 post

### TODO
 1. [x] picture 모델, 마이그레이션 등 설정
 2. [x] multer 이용 그림 이미지 경로 설정
 3. [x] 그림 post controllers

### Estimated time
`2h`
