### ISSUE TITLE
[Task] 내가 그린 꿈 페이지 - 그림 조회 get, 삭제 delete (클라) 

### ISSUE THREAD

**Issue by nala723** [nala723/The-Dreamer#79]
### ISSUE
- Group: client
- Type:  feature
- Detail: 내가 그린 꿈 페이지 - 그림 조회 get, 삭제 delete (클라) 

### TODO
 1. [x] 그림 조회 get 요청 로직
 2. [x] 조회 한 그림 인코딩 후 렌더링
 3. [x] 그림 삭제 delete 요청 로직

### Estimated time
> Pick one
`3h`
